### ISSUE TITLE
Blazor component for resizable floating content holder frame 

### ISSUE THREAD

**Issue by Ayanmullick** [syncfusion/blazor-samples#113]
It would be great if there was a Blazor component that was resizable and that could be repositioned on the browser; like in the screenclip below.

<details>

<summary>Screen clip</summary>

![image](https://camo.githubusercontent.com/4ca304507ae2b6a6445bd961923f06eceb30f4d4e7d0789b43d64ca52ca2fb78/68747470733a2f2f692e696d6775722e636f6d2f4177657730394f2e676966)
</details>

**Comment by kmuthukumar23** [comment]
Hi @Ayanmullick 

Thanks for contacting Syncfusion.

We have validated your query for the availability of resizable and repositionable components in syncfusion blazor components. We want to let you know that we have a component that you want. That has named a 'DashBoard Layout' component. Could you please check the related UG and demo below?

UG: https://blazor.syncfusion.com/documentation/dashboard-layout/getting-started/

Demos: https://blazor.syncfusion.com/demos/dashboard-layout/default

Please let us know if we misunderstood and need any further assistance about this.

Thanks,
Muthukumar K

**Comment by Ayanmullick** [comment]
Thank you for pointing out. I had missed that. Could there be a way to start multiple components with a single `Play` button? If I have a GIF animation, an embedded Powerpoint presentation and a video on 3 different  `e-panel`s , could one start all 3 with one click like below?

![image](https://i.imgur.com/8H5QVWT.gif)

**Comment by Shameer-Ali** [comment]
Hi @Ayanmullick,

We would like to let you know that Blazor Dashboard Layout component is simple, independent component which will render collection of empty panels within its parent element’s dimension(height * width). Since, the requirements on panel content will vary for user DashboardLayout, we have not handle panel content operations.

We can render any HTML elements including Syncfusion Blazor components as the panel content in dashboard panels. 

**DashboardLayout** is a grid structured layout component that helps to create a static and dynamic dashboard layout with panels. Dashboard panels are the basic building blocks of the dashboard and can be added programmatically or dynamically at runtime. The panels hold the UI components and allow resize, reorder, drag-n-drop, remove and add options. This allows users to easily place the components at the desired position within the grid layout.

**Key features**

•	Drag and Drop: Allows drag and drop of panels at the desired location within the dashboard layout.

•	Resizing: Support to resize the panels in any direction as per the requirement.

•	Floating: Floats the panels upward when the dragging option is enabled.

•	Media Query: Allows the panels to be stacked when the specified resolution is met.

Your Query: Could there be a way to start multiple components with a single Play button?  

Since, we don’t handle any panel content operation, it has to be customized based on your requirement.

For your convenience, we have prepared a simple sample of Dashboard Layout with three panels. In each panel, we have added HTML video elements. On clicking a single Play button, three panel videos will play, simultaneously.

Please, download the sample from the following link.

[Demo sample](https://www.syncfusion.com/downloads/support/directtrac/general/ze/BlazorDashboardLayout-311673124.zip) 

To achieve this solution, we have used **JSInterop**. Please, refer the following for more details regarding it.

https://www.syncfusion.com/forums/158628/play-mp4-video-in-blazor 

https://github.com/dotnet/aspnetcore/issues/13233 

Regards,
Shameer Ali Baig S.

**Comment by Ayanmullick** [comment]
Thank you for your detailed response , @Shameer-Ali  and clarifying that `it has to be customized based on your requirement`.
