### ISSUE TITLE
Language detection error

### ISSUE THREAD

**Issue by gitlsl** [syncfusion/blazor-samples#130]
hi，ALL  Your product detects Chinese errors ， recognizes simplified Chinese into traditional Chinese

`simplified Chinese` =  `zh-cn` 
` traditional Chinese`= `zh-tw`

**Comment by Nevitha-Ravi** [comment]
Dear Customer, 

Greetings from Syncfusion Support.

Currently we don’t have separate resx files for Traditional and Simplified Chinese cultures. We have prepared a sample by adding separate resx file for Traditional (zh-TW) and Simplified (zh) files with Kanban component for your reference. Could you please check and let us know your component details to add it in the resx file?
https://www.syncfusion.com/downloads/support/directtrac/general/ze/Localization-sample-1153660382

Regards,
Nevitha

**Comment by gitlsl** [comment]
The  KanBan component  translation after separating resources is correct, but the translation is not very accurate (obvious machine translation). It is recommended to find professional translators for translation or refer to the translation of other control manufacturers

Of course, my words are also translated by machine ~。。~

**Comment by VinithaJeyakumar** [comment]
Hi,

Thanks for your feedback.

We will correct the inaccurate translation resources in **kanban** control and it will be available in any of our upcoming releases.

Regards,
Vinitha.

**Comment by VinithaJeyakumar** [comment]
Hi,


We have included the fix for the issue “**Need to correct the inaccurate translation resources in Kanban Chinese language**” with our 2021 Volume 3 release. Please update your package to the latest version to resolve the issue from your end.

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Vinitha
