### ISSUE TITLE
Keyboard events, Custom Column Editor and navigation in datagrid

### ISSUE THREAD

**Issue by hintsofttech** [syncfusion/blazor-samples#137]
Dear sir/mam, 

we want fully keyboard controllable datagrid with the following features.

1. edit every cell with our own custom textbox i.e. **custom editor for every column**

2. we also want across navigation (next column of row until end and then first col of next row) 
by **enter key instead of tab key.**

3. can we get **entercell, cell keydown, cellleave event** etc kind of events for more customizations for editing ?

can we achieve the above results inside syncfusion blazor datagrid ?

**Comment by hintsofttech** [comment]
sir, seems this is dummy repo...

**Comment by VigneshNatarajan27** [comment]
Hi sir/mam

Qtn: edit every cell with our own custom textbox i.e. custom editor for every column

Ans: 
Yes, we can achieve your requirements using the Syncfusion Blazor DataGrid component. We have built-in support to achieve your requirement of customizing every cell with a custom textbox. We have support for 5 different editor components as editor control for the Grid column. 
If you want to have your own custom component or other editor components, we can achieve this requirement using Cell EditTemplate feature of Grid. 

Qtn: we also want across navigation (next column of the row until end and then first col of next row) by enter key instead of the tab key. can we get enter cell, cell key-down, cell leave event, etc kinds of events for more customizations for editing?

Ans: 
We would like to inform you that Grid edit form will be rendered dynamically based on the specific action (add/edit), so customizing these default actions by binding these enter cell, cell key-down, cell leave are not possible using C# way. But we can achieve this requirement by binding these event using the JavaScript interop function by finding the Grid edit form in javascript side. 

Kindly refer to this documentation for your reference. We have provided support for OnCellSave, OnCellEdit, CellSaved events which will be triggered during the batch edit mode. Please get back to us if you have further queries.

**Comment by VigneshNatarajan27** [comment]
Hi sir/mam

Qtn: edit every cell with our own custom textbox i.e. custom editor for every column
[](url)
Ans: 
Yes, we can achieve your requirements using the Syncfusion Blazor DataGrid component. We have built-in (https://blazor.syncfusion.com/documentation/datagrid/editing#normal) support to achieve your requirement of customizing the every cell with custom textbox. We have support for 5 different editor (https://blazor.syncfusion.com/documentation/datagrid/editing#cell-edit-type) component as editor control for the Grid column. 
If you want to have your own custom component or other editor components, we can achieve this requirement using Cell EditTemplate (https://blazor.syncfusion.com/documentation/datagrid/editing#cell-edit-template) feature of Grid. 

Qtn: we also want across navigation (next column of row until end and then first col of next row) by enter key instead of tab key. can we get entercell, cell keydown, cellleave event etc kind of events for more customizations for editing ?

Ans: 
We would like to inform you that the Grid edit form will be rendered dynamically based on the specific action (add/edit), so we do not have direct support to customizing these default actions by binding these enter cell, cell key down, cell leave events. But we can achieve this requirement by binding these event using the JavaScript interop function by finding the Grid edit form on the javascript side. 

Kindly refer to this documentation (https://blazor.syncfusion.com/documentation/datagrid/events) for your reference. We have provided support for OnCellSave, OnCellEdit, CellSaved event which will be triggered during the batch edit mode. Please get back to us if you have further queries.

**Comment by hintsofttech** [comment]
Dear Sir,
we are searching for at least below two features
1. **Across Navigation** to next column instead of below by **Enter Key**
2. **Fully Unbound DataGrid** without passing any datasource.
3. custom edittemplate not responding to keydown event..

Regards-
Sanjeeb
