### ISSUE TITLE
SfGrid + third-party icons incompatibility

### ISSUE THREAD

**Issue by thepra** [syncfusion/blazor-samples#158]
From the documentation I've found no other way to replace those default icons that right now are displayed as such:
![immagine](https://github.com/syncfusion/blazor-samples/assets/7032509/aed2687b-78b5-4204-a615-cfceb5e441db)

with a custom template for the pagination... do I really need to write the whole pagination template in order to *just* have my third party icons working?(they are from fontawesome in this case)

**Comment by VigneshNatarajan27** [comment]
**Query: “do I really need to write the whole pagination template in order to just have my third party icons working?(they are from fontawesome in this case)”**

As per your requirement we have achieved your requirement of displaying the font awesome icons by applying the CSS styles using the class name used in that buttons. Refer to the below code example. 

```
<style>
    .e-pager .e-icon-first::before{
        content: "\f0a8";
        font-family: "Font Awesome 5 Free";
        font-weight: 900;
    } 
    
    .e-pager .e-icon-last::before{
     
        content: "\f0a9";
        font-family: "Font Awesome 5 Free";
        font-weight: 900;
    }

    .e-pager .e-icon-prev::before {
        content: "\f137";
        font-family: "Font Awesome 5 Free";
        font-weight: 900;
    }
    
    .e-pager .e-icon-next::before {
        content: "\f138";
        font-family: "Font Awesome 5 Free";
        font-weight: 900;
    }

</style>
```


Without using pager template icons can be modified using the CSS styles only. Class name cannot be added to existing pager button. So to apply font awesome icons, we suggest you to styles applied to class name (fas fa-chevron-circle) to default grid class name as specified above. 

Sample: https://blazorplayground.syncfusion.com/rtrgishqKagFCqPk 

Please get back to us if you have further queries.

**Comment by thepra** [comment]
Should work, thanks.
