### ISSUE TITLE
Highlight selected nodes

### ISSUE THREAD

**Issue by endeffects** [syncfusion/blazor-samples#48]
I'd like to highlight the selected node(s) by changing the border / stroke color.
I've found an example for an other framework on your forum that seems to fit my requirements: 
https://www.syncfusion.com/forums/129334/typescript-diagram-highlight-a-series-of-nodes

But this seems to be not supported right now due the missing event handling api, or?

**Comment by RamyaThiru** [comment]
Hi,

Requirement: To customize the appearance of the node when selecting it

The requirement can be achieved by using “SelectionChange” event of the Diagram. Currently, we have deprecated this event due to provide call back support for runtime changes notification events (ConnectionChange and SelectionChange). We have already logged the feature report for this. We will implement and include this support in our Volume 3 release on October 2019. We will get back to you once our Volume 3 is released.

Now, you can track the status of your request through the below feedback link.

Link: https://www.syncfusion.com/feedback/7005/call-back-support-for-the-runtime-changes-notification-events

Regards,
Ramya T

**Comment by Sridhar-Narasimhan** [comment]
We have provided selection change event support to blazor diagram component, So we can close this report. Please find the following link.   
         
**Documentation link:** https://ej2.syncfusion.com/documentation/diagram/getting-started/?no-cache=1    
**Sample Browser Link:** https://ej2.syncfusion.com/demos/#/material/diagram/flow-execution.html
