### ISSUE TITLE
EjsMaps inside of a SplitterPane 

### ISSUE THREAD

**Issue by honkmother** [syncfusion/blazor-samples#56]
I am trying to get the EjsMaps component to work inside of a re-sizable SplitterPane but the results are unpredictable. Sometimes it resizes, sometimes it doesn't and markers don't seem to function properly.

Is there a specific way I am supposed to use the two components together or is it not supported?

**Comment by pandiyarajm** [comment]
Hi @honkmother ,

**Query 1: I am trying to get the EjsMaps component to work inside of a re-sizable SplitterPane but the results are unpredictable. Sometimes it resizes, sometimes it doesn't**

We validated your reported issue and we suspect that you have rendered Maps component using content template of Splitter component. We are able to reproduce the reported resizing issue while rendering Maps component inside content template of Splitter alone. We confirmed this issue as bug on _Splitter_ component. We will resolve and include the fix in the upcoming Nuget patch release, which is expected on 1st week of September.
 
We can also render Maps component as direct HTML content in Splitter like mentioned in the following example.

**Sample code block**

`<EjsSplitter>
    <SplitterPanes>
        <SplitterPane>
            <div> Sample Content </div>
        </SplitterPane>
        <SplitterPane>
            <EjsMaps></EjsMaps>
        </SplitterPane>
    </SplitterPanes>
</EjsSplitter>
`

We have prepared sample for your reference, get if from below link
https://www.syncfusion.com/downloads/support/directtrac/245810/ze/SplitterWithMaps-44775152

**Query 2: markers don't seem to function properly.** 

Since we are not aware of the exact scenario of this reported issue. Could you provide the screenshot of the reported issue and replication steps which will be helpful to investigate further on this reported issue and thus we will provide the solution quickly. 

Regards,
Pandiyaraj M
