### ISSUE TITLE
Source code not showing for all samples

### ISSUE THREAD

**Issue by ozzioma** [syncfusion/blazor-samples#89]
The source code tab for all the examples is not showing the source codes.
When you click on it, it shows up blank.

Like these below

![image](https://user-images.githubusercontent.com/1046981/77958774-71b87e80-72cd-11ea-8478-2eb4780e209b.png)

![image](https://user-images.githubusercontent.com/1046981/77958855-9a407880-72cd-11ea-9e47-e51d4723c16e.png)

What's the solution please?

Thanks

**Comment by Saranya13** [comment]
Hi @ozzioma ,

We have checked your reported issue with GitHub Blazor samples and the issue is not reproduced from our end. Source code is showing for all components. Please find the below images.
![Screenshot (89)](https://user-images.githubusercontent.com/38315832/78147752-93db0980-7451-11ea-9111-713fc428331d.png)

![Screenshot (90)](https://user-images.githubusercontent.com/38315832/78147911-c8e75c00-7451-11ea-83a0-eea9e22b8d80.png)


We have suspected that this issue may be occurred due to the cache problem. Once clear the cache and recheck the samples. Still, if you face the same issue, please share the below details for us?

1. Share the browser Details ( Browser name with version)
2. Share us the stack trace of script error from the browser console.
3. Provide us the dotnet SDK version, you can run the command line dotnet --info in the command prompt to get this.
4. If you run this samples in Visual studio, please share the Visual studio version.

It will be helpful to focus on a specific area and assist you at the earliest. 

Regards,
Saranya M

**Comment by ozzioma** [comment]
Hi Saranya,

I tried on all the browsers on my laptop and the results are the same, the source code tab is not displaying still.
The details you requested for are below
1.  Chrome (Version 80.0.3987.149 (Official Build) (64-bit)), Firefox (74.0 (64-bit))

2. 
![image](https://user-images.githubusercontent.com/1046981/78161383-405ec080-743d-11ea-83e9-6af106996635.png)

3. 
![image](https://user-images.githubusercontent.com/1046981/78161541-8156d500-743d-11ea-936b-a47dff36cc2d.png)


4. The latest source code from Github has errors, as some entity classes were not included in the latest push or release, See here for yourself
![image](https://user-images.githubusercontent.com/1046981/78161931-14900a80-743e-11ea-8ad6-e37bd3d7bcab.png)


Regards,
Ozioma

**Comment by Saranya13** [comment]
Hi @ozzioma ,

We would like to let you know that, the latest version of github samples are working fine. Please find the below link.

https://github.com/syncfusion/blazor-samples

You can pull the latest changes to update your repository.

Please let us know if you have any concerns.

Regards,
Saranya M
